sudo: false

language: scala

jdk:
  - oraclejdk8
  - oraclejdk9

before_cache:
  - find $HOME/.sbt -name '*.lock' -delete
  - find $HOME/.ivy2 -name 'ivydata-*.properties' -delete

script:
  - sbt test